term.clear()
term.setCursorPos(1,1)

term.setCursorPos(20, 3)
term.setTextColor(32)
term.write(" tmczOS ")
term.setTextColor(1)
term.setCursorPos(13, 5)
term.write("Willkommen in der Konsole")
term.setCursorPos(13, 6)
term.write("   Um zurück zu kommen   ")
term.setCursorPos(13, 7)
term.write("      halte STRG + T     ")
term.setCursorPos(13, 8)
term.write("   oder gebe \"exit\" ein  ")
term.setCursorPos(20, 9)
shell.run("rom/programs/shell")
