function clear()
 term.clear()
 term.setCursorPos(1,1)
end

monitor = peripheral.wrap("top")

clear()
local image = paintutils.loadImage("tmczos/logo.nfp")

paintutils.drawImage(image, 1, 1)
term.setBackgroundColor(32768)
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(1)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 1%")
print ("")
print ("              ____________________")
print ("             |                    |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 2%")
print ("")
print ("              ____________________")
print ("             |                    |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 3%")
print ("")
print ("              ____________________")
print ("             |                    |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 4%")
print ("")
print ("              ____________________")
print ("             |                    |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 5%")
print ("")
print ("              ____________________")
print ("             |#                   |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 6%")
print ("")
print ("              ____________________")
print ("             |#                   |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 7%")
print ("")
print ("              ____________________")
print ("             |#                   |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 8%")
print ("")
print ("              ____________________")
print ("             |#                   |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 9%")
print ("")
print ("              ____________________")
print ("             |#                   |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 10%")
print ("")
print ("              ____________________")
print ("             |##                  |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 11%")
print ("")
print ("              ____________________")
print ("             |##                  |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 12%")
print ("")
print ("              ____________________")
print ("             |##                  |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 13%")
print ("")
print ("              ____________________")
print ("             |##                  |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 14%")
print ("")
print ("              ____________________")
print ("             |##                  |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 15%")
print ("")
print ("              ____________________")
print ("             |###                 |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 16%")
print ("")
print ("              ____________________")
print ("             |###                 |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 17%")
print ("")
print ("              ____________________")
print ("             |###                 |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 18%")
print ("")
print ("              ____________________")
print ("             |###                 |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 19%")
print ("")
print ("              ____________________")
print ("             |###                 |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 20%")
print ("")
print ("              ____________________")
print ("             |####                |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 21%")
print ("")
print ("              ____________________")
print ("             |####                |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 22%")
print ("")
print ("              ____________________")
print ("             |####                |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 23%")
print ("")
print ("              ____________________")
print ("             |####                |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 24%")
print ("")
print ("              ____________________")
print ("             |####                |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 25%")
print ("")
print ("              ____________________")
print ("             |#####               |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 26%")
print ("")
print ("              ____________________")
print ("             |#####               |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 27%")
print ("")
print ("              ____________________")
print ("             |#####               |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 28%")
print ("")
print ("              ____________________")
print ("             |#####               |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 29%")
print ("")
print ("              ____________________")
print ("             |#####               |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 30%")
print ("")
print ("              ____________________")
print ("             |######              |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 31%")
print ("")
print ("              ____________________")
print ("             |######              |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 32%")
print ("")
print ("              ____________________")
print ("             |######              |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 33%")
print ("")
print ("              ____________________")
print ("             |######              |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 34%")
print ("")
print ("              ____________________")
print ("             |######              |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 35%")
print ("")
print ("              ____________________")
print ("             |#######             |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 36%")
print ("")
print ("              ____________________")
print ("             |#######             |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 37%")
print ("")
print ("              ____________________")
print ("             |#######             |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 38%")
print ("")
print ("              ____________________")
print ("             |#######             |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 39%")
print ("")
print ("              ____________________")
print ("             |#######             |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 40%")
print ("")
print ("              ____________________")
print ("             |########            |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 41%")
print ("")
print ("              ____________________")
print ("             |########            |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 42%")
print ("")
print ("              ____________________")
print ("             |########            |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 43%")
print ("")
print ("              ____________________")
print ("             |########            |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 44%")
print ("")
print ("              ____________________")
print ("             |########            |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 45%")
print ("")
print ("              ____________________")
print ("             |#########           |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 46%")
print ("")
print ("              ____________________")
print ("             |#########           |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 47%")
print ("")
print ("              ____________________")
print ("             |#########           |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 48%")
print ("")
print ("              ____________________")
print ("             |#########           |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 49%")
print ("")
print ("              ____________________")
print ("             |#########           |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 50%")
print ("")
print ("              ____________________")
print ("             |##########          |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 51%")
print ("")
print ("              ____________________")
print ("             |##########          |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 52%")
print ("")
print ("              ____________________")
print ("             |##########          |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 53%")
print ("")
print ("              ____________________")
print ("             |##########          |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 54%")
print ("")
print ("              ____________________")
print ("             |##########          |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 55%")
print ("")
print ("              ____________________")
print ("             |###########         |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 56%")
print ("")
print ("              ____________________")
print ("             |###########         |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 57%")
print ("")
print ("              ____________________")
print ("             |###########         |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 58%")
print ("")
print ("              ____________________")
print ("             |###########         |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 59%")
print ("")
print ("              ____________________")
print ("             |###########         |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 60%")
print ("")
print ("              ____________________")
print ("             |############        |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 61%")
print ("")
print ("              ____________________")
print ("             |############        |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 62%")
print ("")
print ("              ____________________")
print ("             |############        |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 63%")
print ("")
print ("              ____________________")
print ("             |############        |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 64%")
print ("")
print ("              ____________________")
print ("             |############        |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 65%")
print ("")
print ("              ____________________")
print ("             |#############       |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 66%")
print ("")
print ("              ____________________")
print ("             |#############       |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 67%")
print ("")
print ("              ____________________")
print ("             |#############       |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 68%")
print ("")
print ("              ____________________")
print ("             |#############       |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 69%")
print ("")
print ("              ____________________")
print ("             |#############       |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 70%")
print ("")
print ("              ____________________")
print ("             |##############      |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 71%")
print ("")
print ("              ____________________")
print ("             |##############      |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 72%")
print ("")
print ("              ____________________")
print ("             |##############      |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 73%")
print ("")
print ("              ____________________")
print ("             |##############      |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 74%")
print ("")
print ("              ____________________")
print ("             |##############      |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 75%")
print ("")
print ("              ____________________")
print ("             |###############     |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 76%")
print ("")
print ("              ____________________")
print ("             |###############     |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 77%")
print ("")
print ("              ____________________")
print ("             |###############     |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 78%")
print ("")
print ("              ____________________")
print ("             |###############     |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 79%")
print ("")
print ("              ____________________")
print ("             |###############     |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 80%")
print ("")
print ("              ____________________")
print ("             |################    |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 81%")
print ("")
print ("              ____________________")
print ("             |################    |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 82%")
print ("")
print ("              ____________________")
print ("             |################    |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 83%")
print ("")
print ("              ____________________")
print ("             |################    |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 84%")
print ("")
print ("              ____________________")
print ("             |################    |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 85%")
print ("")
print ("              ____________________")
print ("             |#################   |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 86%")
print ("")
print ("              ____________________")
print ("             |#################   |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 87%")
print ("")
print ("              ____________________")
print ("             |#################   |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 88%")
print ("")
print ("              ____________________")
print ("             |#################   |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 89%")
print ("")
print ("              ____________________")
print ("             |#################   |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 90%")
print ("")
print ("              ____________________")
print ("             |##################  |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 91%")
print ("")
print ("              ____________________")
print ("             |##################  |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 92%")
print ("")
print ("              ____________________")
print ("             |##################  |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 93%")
print ("")
print ("              ____________________")
print ("             |##################  |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 94%")
print ("")
print ("              ____________________")
print ("             |##################  |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 95%")
print ("")
print ("              ____________________")
print ("             |################### |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 96%")
print ("")
print ("              ____________________")
print ("             |################### |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 97%")
print ("")
print ("              ____________________")
print ("             |################### |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 98%")
print ("")
print ("              ____________________")
print ("             |################### |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 99%")
print ("")
print ("              ____________________")
print ("             |################### |")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.01)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS 100%")
print ("")
print ("              ____________________")
print ("             |####################|")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.5)

clear()
term.setCursorPos(1,6)
print ("                Loading tmczOS Complete")
print ("")
print ("              ____________________")
print ("             |####################|")
print ("              --------------------")
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.1)

clear()
paintutils.drawImage(image, 1, 1)
term.setBackgroundColor(32768)
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(1)

clear()
shell.run('tmczos/menu')
