shell.run('rm /startup /tmczos /exit.lua')

fs.copy("disk/.program.lua", "startup")
fs.copy("disk/.logo.nfp", "tmczos/logo.nfp")
fs.copy("disk/.alarm.lua", "tmczos/alarm.lua")
fs.copy("disk/.alarmf.lua", "tmczos/alarmf.lua")
fs.copy("disk/.fabrik.lua", "tmczos/fabrik.lua")
fs.copy("disk/.menu.lua", "tmczos/menu.lua")
fs.copy("disk/.files.lua", "tmczos/files.lua")
fs.copy("disk/.get.lua", "tmczos/get.lua")
fs.copy("disk/.vget.lua", "tmczos/vget.lua")
fs.copy("disk/.exit.lua", "exit.lua")
fs.copy("disk/.console.lua", "tmczos/console.lua")
fs.copy("disk/.musicplayer.lua", "tmczos/musicplayer.lua")
fs.copy("disk/uninstall.lua", "tmczos/uninstall.lua")
fs.copy("disk/.bahnhof.lua", "tmczos/bahnhof.lua")
fs.copy("disk/.bget.lua", "tmczos/bget.lua")
fs.copy("disk/.BryButtonAPI", "tmczos/BryButtonAPI")

function clear()
    term.clear()
    term.setCursorPos(1,1)
   end
   
clear()

local image = paintutils.loadImage("disk/.logo.nfp")
paintutils.drawImage(image, 1, 1)
term.setBackgroundColor(32768)
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(5)

   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 1%")
   print ("")
   print ("              ____________________")
   print ("             |                    |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 2%")
   print ("")
   print ("              ____________________")
   print ("             |                    |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 3%")
   print ("")
   print ("              ____________________")
   print ("             |                    |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 4%")
   print ("")
   print ("              ____________________")
   print ("             |                    |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 5%")
   print ("")
   print ("              ____________________")
   print ("             |#                   |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 6%")
   print ("")
   print ("              ____________________")
   print ("             |#                   |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 7%")
   print ("")
   print ("              ____________________")
   print ("             |#                   |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 8%")
   print ("")
   print ("              ____________________")
   print ("             |#                   |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 9%")
   print ("")
   print ("              ____________________")
   print ("             |#                   |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 10%")
   print ("")
   print ("              ____________________")
   print ("             |##                  |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 11%")
   print ("")
   print ("              ____________________")
   print ("             |##                  |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 12%")
   print ("")
   print ("              ____________________")
   print ("             |##                  |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 13%")
   print ("")
   print ("              ____________________")
   print ("             |##                  |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 14%")
   print ("")
   print ("              ____________________")
   print ("             |##                  |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 15%")
   print ("")
   print ("              ____________________")
   print ("             |###                 |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 16%")
   print ("")
   print ("              ____________________")
   print ("             |###                 |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 17%")
   print ("")
   print ("              ____________________")
   print ("             |###                 |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 18%")
   print ("")
   print ("              ____________________")
   print ("             |###                 |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 19%")
   print ("")
   print ("              ____________________")
   print ("             |###                 |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 20%")
   print ("")
   print ("              ____________________")
   print ("             |####                |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 21%")
   print ("")
   print ("              ____________________")
   print ("             |####                |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 22%")
   print ("")
   print ("              ____________________")
   print ("             |####                |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 23%")
   print ("")
   print ("              ____________________")
   print ("             |####                |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 24%")
   print ("")
   print ("              ____________________")
   print ("             |####                |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 25%")
   print ("")
   print ("              ____________________")
   print ("             |#####               |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 26%")
   print ("")
   print ("              ____________________")
   print ("             |#####               |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 27%")
   print ("")
   print ("              ____________________")
   print ("             |#####               |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 28%")
   print ("")
   print ("              ____________________")
   print ("             |#####               |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 29%")
   print ("")
   print ("              ____________________")
   print ("             |#####               |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 30%")
   print ("")
   print ("              ____________________")
   print ("             |######              |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 31%")
   print ("")
   print ("              ____________________")
   print ("             |######              |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 32%")
   print ("")
   print ("              ____________________")
   print ("             |######              |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 33%")
   print ("")
   print ("              ____________________")
   print ("             |######              |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 34%")
   print ("")
   print ("              ____________________")
   print ("             |######              |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 35%")
   print ("")
   print ("              ____________________")
   print ("             |#######             |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 36%")
   print ("")
   print ("              ____________________")
   print ("             |#######             |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 37%")
   print ("")
   print ("              ____________________")
   print ("             |#######             |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 38%")
   print ("")
   print ("              ____________________")
   print ("             |#######             |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 39%")
   print ("")
   print ("              ____________________")
   print ("             |#######             |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 40%")
   print ("")
   print ("              ____________________")
   print ("             |########            |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 41%")
   print ("")
   print ("              ____________________")
   print ("             |########            |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 42%")
   print ("")
   print ("              ____________________")
   print ("             |########            |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 43%")
   print ("")
   print ("              ____________________")
   print ("             |########            |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 44%")
   print ("")
   print ("              ____________________")
   print ("             |########            |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 45%")
   print ("")
   print ("              ____________________")
   print ("             |#########           |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 46%")
   print ("")
   print ("              ____________________")
   print ("             |#########           |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 47%")
   print ("")
   print ("              ____________________")
   print ("             |#########           |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 48%")
   print ("")
   print ("              ____________________")
   print ("             |#########           |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 49%")
   print ("")
   print ("              ____________________")
   print ("             |#########           |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 50%")
   print ("")
   print ("              ____________________")
   print ("             |##########          |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 51%")
   print ("")
   print ("              ____________________")
   print ("             |##########          |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 52%")
   print ("")
   print ("              ____________________")
   print ("             |##########          |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 53%")
   print ("")
   print ("              ____________________")
   print ("             |##########          |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 54%")
   print ("")
   print ("              ____________________")
   print ("             |##########          |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 55%")
   print ("")
   print ("              ____________________")
   print ("             |###########         |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 56%")
   print ("")
   print ("              ____________________")
   print ("             |###########         |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 57%")
   print ("")
   print ("              ____________________")
   print ("             |###########         |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 58%")
   print ("")
   print ("              ____________________")
   print ("             |###########         |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 59%")
   print ("")
   print ("              ____________________")
   print ("             |###########         |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 60%")
   print ("")
   print ("              ____________________")
   print ("             |############        |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 61%")
   print ("")
   print ("              ____________________")
   print ("             |############        |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 62%")
   print ("")
   print ("              ____________________")
   print ("             |############        |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 63%")
   print ("")
   print ("              ____________________")
   print ("             |############        |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 64%")
   print ("")
   print ("              ____________________")
   print ("             |############        |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 65%")
   print ("")
   print ("              ____________________")
   print ("             |#############       |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 66%")
   print ("")
   print ("              ____________________")
   print ("             |#############       |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 67%")
   print ("")
   print ("              ____________________")
   print ("             |#############       |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 68%")
   print ("")
   print ("              ____________________")
   print ("             |#############       |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 69%")
   print ("")
   print ("              ____________________")
   print ("             |#############       |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 70%")
   print ("")
   print ("              ____________________")
   print ("             |##############      |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 71%")
   print ("")
   print ("              ____________________")
   print ("             |##############      |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 72%")
   print ("")
   print ("              ____________________")
   print ("             |##############      |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 73%")
   print ("")
   print ("              ____________________")
   print ("             |##############      |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 74%")
   print ("")
   print ("              ____________________")
   print ("             |##############      |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 75%")
   print ("")
   print ("              ____________________")
   print ("             |###############     |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 76%")
   print ("")
   print ("              ____________________")
   print ("             |###############     |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 77%")
   print ("")
   print ("              ____________________")
   print ("             |###############     |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 78%")
   print ("")
   print ("              ____________________")
   print ("             |###############     |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 79%")
   print ("")
   print ("              ____________________")
   print ("             |###############     |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 80%")
   print ("")
   print ("              ____________________")
   print ("             |################    |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 81%")
   print ("")
   print ("              ____________________")
   print ("             |################    |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 82%")
   print ("")
   print ("              ____________________")
   print ("             |################    |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 83%")
   print ("")
   print ("              ____________________")
   print ("             |################    |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 84%")
   print ("")
   print ("              ____________________")
   print ("             |################    |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 85%")
   print ("")
   print ("              ____________________")
   print ("             |#################   |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 86%")
   print ("")
   print ("              ____________________")
   print ("             |#################   |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 87%")
   print ("")
   print ("              ____________________")
   print ("             |#################   |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 88%")
   print ("")
   print ("              ____________________")
   print ("             |#################   |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 89%")
   print ("")
   print ("              ____________________")
   print ("             |#################   |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 90%")
   print ("")
   print ("              ____________________")
   print ("             |##################  |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 91%")
   print ("")
   print ("              ____________________")
   print ("             |##################  |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 92%")
   print ("")
   print ("              ____________________")
   print ("             |##################  |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 93%")
   print ("")
   print ("              ____________________")
   print ("             |##################  |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 94%")
   print ("")
   print ("              ____________________")
   print ("             |##################  |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 95%")
   print ("")
   print ("              ____________________")
   print ("             |################### |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 96%")
   print ("")
   print ("              ____________________")
   print ("             |################### |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 97%")
   print ("")
   print ("              ____________________")
   print ("             |################### |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 98%")
   print ("")
   print ("              ____________________")
   print ("             |################### |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 99%")
   print ("")
   print ("              ____________________")
   print ("             |################### |")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.1)
   
   clear()
   term.setCursorPos(1,6)
   print ("              Installing tmczOS 100%")
   print ("")
   print ("              ____________________")
   print ("             |####################|")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(0.5)
   
   clear()
   term.setCursorPos(1,6)
   print ("         Installation from tmczOS Complete")
   print ("")
   print ("              ____________________")
   print ("             |####################|")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(1)
   
   clear()
   term.setCursorPos(1,6)
   print ("          Thanks for Installing tmczOS")
   print ("")
   print ("              ____________________")
   print ("             |####################|")
   print ("              --------------------")
   term.setCursorPos(1,17)
   print ("                     tmczOS")
   sleep(1)
shell.run("eject top")
shell.run("eject left")
shell.run("eject right")
os.reboot()
