shell.run('rm /startup /tmczos /exit.lua')

fs.copy("disk/.program.lua", "startup")
fs.copy("disk/.logo.nfp", "tmczos/logo.nfp")
fs.copy("disk/.alarm.lua", "tmczos/alarm.lua")
fs.copy("disk/.alarmf.lua", "tmczos/alarmf.lua")
fs.copy("disk/.fabrik.lua", "tmczos/fabrik.lua")
fs.copy("disk/.menu.lua", "tmczos/menu.lua")
fs.copy("disk/.files.lua", "tmczos/files.lua")
fs.copy("disk/.get.lua", "tmczos/get.lua")
fs.copy("disk/.vget.lua", "tmczos/vget.lua")
fs.copy("disk/.exit.lua", "exit.lua")
fs.copy("disk/.console.lua", "tmczos/console.lua")
fs.copy("disk/.musicplayer.lua", "tmczos/musicplayer.lua")
fs.copy("disk/.bahnhof.lua", "tmczos/bahnhof.lua")
fs.copy("disk/.bget.lua", "tmczos/bget.lua")
fs.copy("disk/uninstall.lua", "tmczos/uninstall.lua")
fs.copy("disk/.BryButtonAPI", "tmczos/BryButtonAPI")

function clear()
    term.clear()
    term.setCursorPos(1,1)
   end
   
clear()

local image = paintutils.loadImage("disk/.logo.nfp")
paintutils.drawImage(image, 1, 1)
term.setBackgroundColor(32768)
sleep(1)
term.clear()
term.setCursorPos(1,1)

term.setCursorPos(20, 3)
term.setTextColor(32)
term.write(" tmczOS ")
term.setTextColor(1)
term.setCursorPos(13, 5)
term.write(" Update wird Installiert ")

term.setCursorPos(1,8)
print("                Updating tmczOS")
term.setCursorPos(17,9)
textutils.slowPrint("###############",2)
term.setCursorPos(1,17)
print ("                     tmczOS")
sleep(0.1)
   
shell.run("eject top")
shell.run("eject left")
shell.run("eject right")
os.reboot()
